# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108dca85a87ec7dc625b5a627feceeac1d4fd4df8e55428913ce442bb34e78eb86a64e4ce8dcc347d86c44a121a61fb2b99fd3c8fe15b23deeadaaa685344711

test:
  secret_key_base: 7feaf8a338a7054be07fa0043b2d12ad8f03633c9c9b2a778cd1de2f3aab637780d1beaf6222a4d14326a82134939c2bd9adb0ec024cd834e77b0c6c887c5818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
